import Head from 'next/head';
import { useQuery } from 'react-query';

//components
import HomeLayout from '@epicapp/layouts/HomeLayout';
import Details from '@epicapp/components/Profile/Details';
import Timeline from '@epicapp/components/Profile/Timeline';

//services
import { getAuthorDetails } from '@epicapp/services/author';

export default function Profile({ id }) {
  const auth = useQuery(['author'], () => getAuthorDetails(null), {
    staleTime: Infinity,
  });

  const profile = useQuery(['profile', id], () => getAuthorDetails(id), {
    staleTime: Infinity,
  });

  return (
    <main className="h-screen w-screen bg-background">
      <Head>
        <title>Epic App: Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      {auth.isLoading || profile.isLoading ? (
        <div className="flex h-full items-center justify-center text-9xl text-primary">
          <i className="fa-solid fa-spinner-third animate-spin bg-transparent text-2xl text-primary" />
        </div>
      ) : (
        <HomeLayout route="PROFILE" author={auth.data?.data}>
          <div className="container">
            <Details auth={auth.data?.data} author={profile?.data?.data} />
            <Timeline auth={auth.data?.data} author={profile?.data?.data} />
          </div>
        </HomeLayout>
      )}
    </main>
  );
}

export async function getServerSideProps(context) {
  if (!context.query.id || !context.req.headers.cookie?.includes('access=')) {
    return {
      props: {},
      redirect: {
        permanent: false,
        destination: '/',
      },
    };
  }
  return {
    props: {
      id: context.query.id,
    },
  };
}
