import Head from 'next/head';
import { useQuery, useQueryClient } from 'react-query';

//components
import HomeLayout from '@epicapp/layouts/HomeLayout';
import Profile from '@epicapp/components/Home/Profile';
import Search from '@epicapp/components/Friends/Search';

//services
import { getAuthorDetails } from '@epicapp/services/author';
import FriendsList from '@epicapp/components/Friends/Friend';

export default function Homepage() {
  const author = useQuery(['author'], getAuthorDetails, {
    retry: 1,
    staleTime: 10000,
  });

  console.log("AUTHOR" + JSON.stringify(author.data?.data))

  return (
    <>
      <Head>
        <title>Epic App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen bg-background overflow-y-auto">
        {author.isLoading ? (
          <div className="flex h-full items-center justify-center text-9xl text-primary">
            {/* // maybe a ekelton loading animation here? */}
            <i className="fa-solid fa-spinner-third text-primary animate-spin bg-transparent text-2xl" />
          </div>
        ) : (
          <HomeLayout route="PROFILE" author={author.data?.data}>
            <div className="grid grid-cols-4 gap-8">
              <section className="col-span-1 w-full">
                <Profile author={author.data?.data} />
              </section>
              <section className="col-span-3 flex flex-col gap-6">
                <Search authorSendingRequest={author} />
                <FriendsList author={author.data?.data} />
              </section>
            </div>
          </HomeLayout>
        )}
      </main>
    </>
  );
}