import Head from 'next/head';
import { useQuery, useQueryClient } from 'react-query';

//components
import HomeLayout from '@epicapp/layouts/HomeLayout';
import Profile from '@epicapp/components/Home/Profile';
import Stream from '@epicapp/components/Home/Stream';

//services
import { getAuthorDetails } from '@epicapp/services/author';

export default function Inbox() {
  const author = useQuery(['author'], getAuthorDetails, {
    staleTime: Infinity,
  });

  return (
    <>
      <Head>
        <title>Epic App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen overflow-y-auto bg-background">
        {author.isLoading ? (
          <div className="flex h-full items-center justify-center text-9xl text-primary">
            {/* // maybe a ekelton loading animation here? */}
            <i className="fa-solid fa-spinner-third animate-spin bg-transparent text-2xl text-primary" />
          </div>
        ) : (
          <HomeLayout route="INBOX" author={author.data?.data}>
            <div className="grid grid-cols-4 gap-8">
              <section className="col-span-1 w-full">
                <Profile author={author.data?.data} />
              </section>
              <section className="col-span-3 flex flex-col gap-6">
                <Stream author={author.data?.data} isInbox={true} />
              </section>
            </div>
          </HomeLayout>
        )}
      </main>
    </>
  );
}
