import Head from 'next/head';

//components
import Signin from '@epicapp/components/SignIn';
import HomeLayout from '@epicapp/layouts/HomeLayout';

export default function SigninPage() {
  return (
    <>
      <Head>
        <title>Epic App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <HomeLayout route="HOME"></HomeLayout>
      </main>
    </>
    // <>
    //   <Head>
    //     <title>Epic App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main className="container mx-auto">
    //     <Signin/>
    //   </main>
    // </>
  );
}
