import Head from 'next/head';

//components
import Signup from '@epicapp/components/Signup';

export default function SignupPage() {
  return (
    <>
      <Head>
        <title>Epic App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <Signup/>
      </main>
    </>
  );
}
